apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ctrl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /messages
spec:
  rules:
  - http:
      paths:
      - path: /messages
        pathType: Prefix
        backend:
          serviceName: message-receiver-svc
          servicePort: 8080