kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: p1 
    protocol: TCP
    port: 25672
    targetPort: 25672
  - name: p2 
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: p3 
    protocol: TCP
    port: 4369
    targetPort: 4369
  - name: p4 
    protocol: TCP
    port: 15672
    targetPort: 15672